addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - libdbus-1-dev
      - libx11-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxss-dev
      - libglib2.0-dev
      - libpango1.0-dev
      - libcairo2-dev
      - libnotify-dev
      - libgtk-3-dev
      - valgrind
dist: trusty
sudo: false
language: c

git:
  depth: false

before_install:
  - pip install --user cpp-coveralls

  - CFLAGS="-Werror" make all dunstify test-valgrind doc-doxygen
  - CFLAGS="-Werror" make clean
  - CFLAGS="-Werror" make test-coverage
  - find -type f -name '*.[ch]' -not -name greatest.h | xargs clang-format -i
  - [ "$(git status --porcellain | wc -l)" < 1 ] || {git status; git diff; exit 1;}

matrix:
  include:
    - compiler: gcc
      after_success:
        - coveralls
    - compiler: clang
      after_success:
        - coveralls --gcov llvm-cov --gcov-options gcov
